### ISSUE TITLE
Adding new lines in header

### ISSUE THREAD

**Issue by riconaranjo** [CarletonSLAM/CarletonNewsletter#1]
Header text can be modified with toast in `.js` models but this does not seem to support new lines.

This means header text is all on one line, unless html is modified manually after build. It would be nice to be able to add multiple paragraphs in header text [toast].

**Comment by irushavm** [comment]
Need to add a parser that replaces newlines in toast variable with `</p><p>` in https://github.com/CarletonSLAM/CarletonNewsletter/blob/master/components/Header/index.jsx#L11
